import { Flex, Text } from "@chakra-ui/react";


export const form = {

    title: 'Ainda não sei se tenho um antepassado italiano',
    subtitle: <>Com uma combinação única de pesquisa genealógica avançada e assistência legal, <b>o EuroLink</b> que te permite descobrir se existem antepassados europeus em sua linhagem, e comprová-lo oficialmente para adquirir sua cidadania.</>,
    inputs: {
        name: 'SEU NOME COMPLETO',
        whatsapp: "SEU WHATSAPP"
    }

}


const ddis = [
    { country: 'Brasil', value: '+55' },
    { country: 'Afghanistão', value: '+93' },
    { country: 'África do Sul', value: '+27' },
    { country: 'Albânia', value: '+355' },
    { country: 'Alemanha', value: '+49' },
    { country: 'Andora', value: '+376' },
    { country: 'Angola', value: '+244' },
    { country: 'Antarctica', value: '+672' },
    { country: 'Argentina', value: '+54' },
    { country: 'Argélia', value: '+213' },
    { country: 'Arménia', value: '+374' },
    { country: 'Aruba', value: '+297' },
    { country: 'Arábia Saudita', value: '+966' },
    { country: 'Austrália', value: '+61' },
    { country: 'Áustria', value: '+43' },
    { country: 'Azerbaijão', value: '+994' },
    { country: 'Bahrein', value: '+973' },
    { country: 'Bangladesh', value: '+880' },
    { country: 'Bélgica', value: '+32' },
    { country: 'Belize', value: '+501' },
    { country: 'Benim', value: '+229' },
    { country: 'Butão', value: '+975' },
    { country: 'Bielorrússia', value: '+375' },
    { country: 'Bolívia', value: '+591' },
    { country: 'Bósnia e Herzegovina', value: '+387' },
    { country: 'Botswana', value: '+267' },
    { country: 'Brunei', value: '+673' },
    { country: 'Bulgária', value: '+359' },
    { country: 'Burkina Faso', value: '+226' },
    { country: 'Myanmar (Burma)', value: '+95' },
    { country: 'Burundi', value: '+257' },
    { country: 'Camarões', value: '+237' },
    { country: 'Cabo Verde', value: '+238' },
    { country: 'Camboja', value: '+855' },
    { country: 'Canadá', value: '+1' },
    { country: 'Catar', value: '+974' },
    { country: 'Chad', value: '+235' },
    { country: 'Chile', value: '+56' },
    { country: 'China', value: '+86' },
    { country: 'Chipre', value: '+357' },
    { country: 'Christmas Island', value: '+61' },
    { country: 'Cingapura', value: '+65' },
    { country: 'Colômbia', value: '+57' },
    { country: 'Comores', value: '+269' },
    { country: 'Coreia do Norte', value: '+850' },
    { country: 'Coreia do Sul', value: '+82' },
    { country: 'Costa do Marfim', value: '+225' },
    { country: 'Costa Rica', value: '+506' },
    { country: 'Croácia', value: '+385' },
    { country: 'Cuba', value: '+53' },
    { country: 'Dinamarca', value: '+45' },
    { country: 'Djibouti', value: '+253' },
    { country: 'Egito', value: '+20' },
    { country: 'El Salvador', value: '+503' },
    { country: 'Emirados Árabes Unidos', value: '+971' },
    { country: 'Equador', value: '+593' },
    { country: 'Eritreia', value: '+291' },
    { country: 'Estónia', value: '+372' },
    { country: 'Espanha', value: '+34' },
    { country: 'Etiópia', value: '+251' },
    { country: 'Fiji', value: '+679' },
    { country: 'Finlândia', value: '+358' },
    { country: 'França', value: '+33' },
    { country: 'Gabão', value: '+241' },
    { country: 'Gâmbia', value: '+220' },
    { country: 'Banda de Gaza (Palestina)', value: '+970' },
    { country: 'Geórgia', value: '+995' },
    { country: 'Gana', value: '+233' },
    { country: 'Gibraltar', value: '+350' },
    { country: 'Grécia', value: '+30' },
    { country: 'Groelândia', value: '+299' },
    { country: 'Guatemala', value: '+502' },
    { country: 'Guiana', value: '+592' },
    { country: 'Guiné', value: '+224' },
    { country: 'Guiné Equatorial', value: '+240' },
    { country: 'Guiné-Bissau', value: '+245' },
    { country: 'Haiti', value: '+509' },
    { country: 'Honduras', value: '+504' },
    { country: 'Hong Kong', value: '+852' },
    { country: 'Hungria', value: '+36' },
    { country: 'Islândia', value: '+354' },
    { country: 'Ilhas Cocos (Keeling)', value: '+61' },
    { country: 'Ilha de Man', value: '+44' },
    { country: 'Ilhas Cook', value: '+682' },
    { country: 'Ilhas Falkland (Malvinas)', value: '+500' },
    { country: 'Ilhas Feroé', value: '+298' },
    { country: 'Ilhas Marshall', value: '+692' },
    { country: 'Ilhas Norfolk', value: '+672' },
    { country: 'Ilhas Pitcairn', value: '+870' },
    { country: 'Ilhas Salomão', value: '+677' },
    { country: 'India', value: '+91' },
    { country: 'Indonésia', value: '+62' },
    { country: 'Inglaterra (Reino Unido)', value: '+44' },
    { country: 'Irã', value: '+98' },
    { country: 'Iraque', value: '+964' },
    { country: 'Irlanda', value: '+353' },
    { country: 'Israel', value: '+972' },
    { country: 'Itália', value: '+39' },
    { country: 'Japão', value: '+81' },
    { country: 'Jordânia', value: '+962' },
    { country: 'Cazaquistão', value: '+7' },
    { country: 'Quénia (Kenya)', value: '+254' },
    { country: 'Kiribati', value: '+686' },
    { country: 'Kosovo', value: '+381' },
    { country: 'Kuwait', value: '+965' },
    { country: 'Quirguistão', value: '+996' },
    { country: 'Laos', value: '+856' },
    { country: 'Letônia', value: '+371' },
    { country: 'Líbano', value: '+961' },
    { country: 'Lesoto', value: '+266' },
    { country: 'Libéria', value: '+231' },
    { country: 'Líbia', value: '+218' },
    { country: 'Liechtenstein', value: '+423' },
    { country: 'Lituânia', value: '+370' },
    { country: 'Luxemburgo', value: '+352' },
    { country: 'Macau', value: '+853' },
    { country: 'Macedónia', value: '+389' },
    { country: 'Madagáscar', value: '+261' },
    { country: 'Malawi', value: '+265' },
    { country: 'Malásia', value: '+60' },
    { country: 'Maldivas', value: '+960' },
    { country: 'Mali', value: '+223' },
    { country: 'Malta', value: '+356' },
    { country: 'Mauritânia', value: '+222' },
    { country: 'Maurícia', value: '+230' },
    { country: 'Mayotte', value: '+262' },
    { country: 'México', value: '+52' },
    { country: 'Micronésia', value: '+691' },
    { country: 'Moldávia', value: '+373' },
    { country: 'Monaco', value: '+377' },
    { country: 'Mongólia', value: '+976' },
    { country: 'Montenegro', value: '+382' },
    { country: 'Marrocos', value: '+212' },
    { country: 'Moçambique', value: '+258' },
    { country: 'Namíbia', value: '+264' },
    { country: 'Nauru', value: '+674' },
    { country: 'Nepal', value: '+977' },
    { country: 'Netherlands Antilles', value: '+599' },
    { country: 'Nova Caledônia', value: '+687' },
    { country: 'Nova Zelândia', value: '+64' },
    { country: 'Nicaragua', value: '+505' },
    { country: 'Níger', value: '+227' },
    { country: 'Nigéria', value: '+234' },
    { country: 'Niue', value: '+683' },
    { country: 'Noruega', value: '+47' },
    { country: 'Omã', value: '+968' },
    { country: 'Países Baixos', value: '+31' },
    { country: 'Paquistão', value: '+92' },
    { country: 'Palau', value: '+680' },
    { country: 'Panamá', value: '+507' },
    { country: 'Papua-Nova Guiné', value: '+675' },
    { country: 'Paraguai', value: '+595' },
    { country: 'Peru', value: '+51' },
    { country: 'Filipinas', value: '+63' },
    { country: 'Polónia', value: '+48' },
    { country: 'Polinésia Francesa', value: '+689' },
    { country: 'Portugal', value: '+351' },
    { country: 'Porto Rico', value: '+1' },
    { country: 'República do Congo', value: '+242' },
    { country: 'República Democrática do Congo', value: '+243' },
    { country: 'República Centro-Africana', value: '+236' },
    { country: 'República Checa', value: '+420' },
    { country: 'Roménia', value: '+40' },
    { country: 'Ruanda', value: '+250' },
    { country: 'Rússia', value: '+7' },
    { country: 'Saint Barthelemy', value: '+590' },
    { country: 'Samoa', value: '+685' },
    { country: 'San Marino', value: '+378' },
    { country: 'Sao Tome e Principe', value: '+239' },
    { country: 'Senegal', value: '+221' },
    { country: 'Serbia', value: '+381' },
    { country: 'Serra Leoa', value: '+232' },
    { country: 'Seychelles', value: '+248' },
    { country: 'Slovakia', value: '+421' },
    { country: 'Slovenia', value: '+386' },
    { country: 'Somalia', value: '+252' },
    { country: 'Sri Lanka', value: '+94' },
    { country: 'Saint Helena', value: '+290' },
    { country: 'Saint Pierre and Miquelon', value: '+508' },
    { country: 'Sudão', value: '+249' },
    { country: 'Suriname', value: '+597' },
    { country: 'Suazilândia', value: '+268' },
    { country: 'Suécia', value: '+46' },
    { country: 'Suiça', value: '+41' },
    { country: 'Syria', value: '+963' },
    { country: 'Taiwan', value: '+886' },
    { country: 'Tajiquistão', value: '+992' },
    { country: 'Tanzânia', value: '+255' },
    { country: 'Timor-Leste', value: '+670' },
    { country: 'Tailândia', value: '+66' },
    { country: 'Togo', value: '+228' },
    { country: 'Tokelau', value: '+690' },
    { country: 'Tonga', value: '+676' },
    { country: 'Tunísia', value: '+216' },
    { country: 'Turquemenistão', value: '+993' },
    { country: 'Turquia', value: '+90' },
    { country: 'Tuvalu', value: '+688' },
    { country: 'Uganda', value: '+256' },
    { country: 'Ucrânia', value: '+380' },
    { country: 'Uruguai', value: '+598' },
    { country: 'Estados Unidos (EUA)', value: '+1' },
    { country: 'Uzbequistão', value: '+998' },
    { country: 'Vanuatu', value: '+678' },
    { country: 'Vaticano', value: '+39' },
    { country: 'Venezuela', value: '+58' },
    { country: 'Vietnã (Vietname)', value: '+84' },
    { country: 'Wallis e Futuna', value: '+681' },
    { country: 'West Bank', value: '+970' },
    { country: 'Iémen (Iémen, Yemen)', value: '+967' },
    { country: 'Zimbabwe(Zimbabué)', value: '+263' },
    { country: 'Zâmbia', value: '+260' },

]

export {ddis}